site_name: dapla-toolbelt-pseudo
site_description: Pseudonymization extensions for Dapla Toolbelt
site_url: https://statisticsnorway.github.io/dapla-toolbelt-pseudo

theme:
  name: "material"
repo_name: statisticsnorway/dapla-toolbelt-pseudo
repo_url: https://github.com/statisticsnorway/dapla-toolbelt-pseudo
edit_uri: edit/main/docs/

nav:
  - Home: "index.md"
  - Code Reference: reference/
  - Contributing: "CONTRIBUTING.md"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
#      watch:
#        - src/dapla_pseudo

markdown_extensions:
  - admonition #  note blocks, warning blocks -- https://github.com/mkdocs/mkdocs/issues/1659
  - attr_list # Enables full command headers, see https://github.com/DataDog/mkdocs-click#full-command-path-headers
  - mkdocs-typer