import inspect
from collections.abc import Generator

import polars as pl

from dapla_pseudo import Pseudonymize
from tests.integration.utils import df_personer
from tests.integration.utils import get_calling_function_name
from tests.integration.utils import get_expected_datadoc_metadata_container
from tests.integration.utils import integration_test
from tests.integration.utils import setup


@integration_test()
def test_pseudonymize_default_encryption(
    setup: Generator[None, None, None], df_personer: pl.DataFrame
) -> None:
    expected_result_fnr_df = pl.DataFrame(
        {
            "fnr": [
                "AWIRfKLSNfR0ID+wBzogEcUT7JQPayk7Gosij6SXr8s=",
                "AWIRfKKLagk0LqYCKpiC4xfPkHqIWGVfc3wg5gUwRNE=",
                "AWIRfKIzL1T9iZqt+pLjNbHMsLa0aKSszsRrLiLSAAg=",
            ]
        }
    )
    expected_result_df = df_personer.clone().update(expected_result_fnr_df)
    result = (
        Pseudonymize.from_polars(df_personer)
        .on_fields("fnr")
        .with_default_encryption()
        .run()
    )
    current_function_name = get_calling_function_name()
    expected_metadata_container = get_expected_datadoc_metadata_container(
        current_function_name
    )

    assert result.datadoc == expected_metadata_container.model_dump_json()
    assert result.to_polars().equals(expected_result_df)


@integration_test()
def test_pseudonymize_default_encryption_all_fields(
    setup: Generator[None, None, None], df_personer: pl.DataFrame
) -> None:
    expected_result_df = pl.read_json(
        "tests/data/personer_pseudonymized_default_encryption.json"
    )
    result = (
        Pseudonymize.from_polars(df_personer)
        .on_fields(*df_personer.columns)
        .with_default_encryption()
        .run()
    )
    current_function_name = get_calling_function_name()
    expected_metadata_container = get_expected_datadoc_metadata_container(
        current_function_name
    )
    # When comparing the expected metadata with the metadata generated by the API,
    # we need the pseudo_variables to be in the same order. This is not guaranteed by the API
    # `pseudo_variables` are therefore sorted before we make the comparison.
    # In the context of this test we can guarantee that the `short_name` is unique, which allows us to sort by it.
    if (result._datadoc.pseudonymization is not None) and (
        expected_metadata_container.pseudonymization is not None
    ):
        result._datadoc.pseudonymization.pseudo_variables = sorted(
            result._datadoc.pseudonymization.pseudo_variables,
            key=lambda pseudo_var: (
                pseudo_var.short_name if isinstance(pseudo_var.short_name, str) else ""
            ),
        )
        expected_metadata_container.pseudonymization.pseudo_variables = sorted(
            expected_metadata_container.pseudonymization.pseudo_variables,
            key=lambda pseudo_var: (
                pseudo_var.short_name if isinstance(pseudo_var.short_name, str) else ""
            ),
        )

        assert result._datadoc == expected_metadata_container
        assert result.to_polars().equals(expected_result_df)
    else:
        raise AssertionError("MetadataContainer's pseudonymization object is None")


@integration_test()
def test_pseudonymize_default_encryption_null(
    setup: Generator[None, None, None], df_personer: pl.DataFrame
) -> None:
    expected_result_fnr_df = pl.DataFrame(
        {
            "fnr": [
                "AWIRfKLSNfR0ID+wBzogEcUT7JQPayk7Gosij6SXr8s=",
                "AWIRfKKLagk0LqYCKpiC4xfPkHqIWGVfc3wg5gUwRNE=",
                "AWIRfKIzL1T9iZqt+pLjNbHMsLa0aKSszsRrLiLSAAg=",
                None,
            ]
        }
    )
    expected_result_df = df_personer.clone().update(expected_result_fnr_df)

    fnr_values = [*df_personer["fnr"].to_list(), None]

    df_personer = df_personer.update(pl.DataFrame({"fnr": fnr_values}))
    result = (
        Pseudonymize.from_polars(df_personer)
        .on_fields("fnr")
        .with_default_encryption()
        .run()
    )
    current_function_name = get_calling_function_name()
    expected_metadata_container = get_expected_datadoc_metadata_container(
        current_function_name
    )

    assert result._datadoc == expected_metadata_container
    assert result.to_polars().equals(expected_result_df)


@integration_test()
def test_pseudonymize_sid(
    setup: Generator[None, None, None], df_personer: pl.DataFrame
) -> None:
    expected_result_fnr_df = pl.DataFrame(
        {
            "fnr": [
                "jJuuj0i",
                "ylc9488",
                "yeLfkaL",
            ]
        }
    )
    expected_result_df = df_personer.clone().update(expected_result_fnr_df)
    result = (
        Pseudonymize.from_polars(df_personer).on_fields("fnr").with_stable_id().run()
    )
    current_function_name = get_calling_function_name()
    expected_metadata_container = get_expected_datadoc_metadata_container(
        current_function_name
    )
    assert result._datadoc == expected_metadata_container
    assert result.to_polars().equals(expected_result_df)


@integration_test()
def test_pseudonymize_sid_null(
    setup: Generator[None, None, None], df_personer: pl.DataFrame
) -> None:
    expected_result_fnr_df = pl.DataFrame(
        {"fnr": ["jJuuj0i", "ylc9488", "yeLfkaL", None]}
    )
    expected_result_df = df_personer.clone().update(expected_result_fnr_df)

    fnr_values = [*df_personer["fnr"].to_list(), None]

    df_personer = df_personer.update(pl.DataFrame({"fnr": fnr_values}))

    result = (
        Pseudonymize.from_polars(df_personer).on_fields("fnr").with_stable_id().run()
    )
    current_function_name = get_calling_function_name()
    expected_metadata_container = get_expected_datadoc_metadata_container(
        current_function_name
    )

    assert result._datadoc == expected_metadata_container
    assert result.to_polars().equals(expected_result_df)
